Sprint 1
ale0x78ey/yandex-practicum-go-developer-devops pull request #1
Opened 2021-12-28 20:15 UTC by ale0x78ey

2021-12-31 20:05 UTC, iTiky requested changes
Здорово, что ты сразу всё закрываешь тестами. Отправляю на доработку, т.к. текущий код не совсем Go-код. Из критичного - неверное использование контекста.

2021-12-31 20:05 UTC, iTiky commented on api/rest/middleware.go
> +func withServer(srv *server.Server) func(next http.Handler) http.Handler {
Так делать не надо. Контекст нужен для передачи мета-информации о текущем конкретной запросе, он не должен сохранять состояние приложения. Ты сохраняешь туда server, чтобы обратиться к слою логики, это можно сделать иначе:
```go
type Handler struct {
  // тут все зависимости необходимые хендлерам
}

func (h Handler) GetMetrict() http.HandlerFunc {
    return func(w http.ResponseWriter, r *http.Request) {
        // код, который через замыкание получает доступ ко всему, что есть внутри "h Handler"
    }
}
```

2021-12-31 21:20 UTC, ale0x78ey commented on api/rest/metric.go
> +	api.Routes.Metric.Route("/update/{metricType}/{metricName}/{metricValue}",
Да, ок. Я за основу взял https://github.com/mattermost/mattermost-server, кот. на встрече советовали, сам намучился, пока разобрал сервис )

2021-12-31 21:21 UTC, ale0x78ey commented on storage/psql/storage.go
> +package psql
Она самая )

из https://github.com/iTiky/practicum-examples

2022-01-07 11:55 UTC, iTiky approved these changes
Отличный рефакторинг!

2022-01-07 11:55 UTC, iTiky commented on api/rest/api.go
> +	if router == nil {
Это кажется лишним. Да, тут возвращают указатель, но т.к. нету ошибки, подразумеваем что объект всегда будет создан.

2022-01-07 11:55 UTC, iTiky commented on api/rest/api.go
> +	h.initMiddleware()
Я бы убрал эти функции, т.е. сделал инициализацию роутера inline. Смысл тот же, но удобнее когда вся "карта" ендпоинтов перед глазами (включая мидлвари) и не нужно искать ее по коду. Личное ИМХО

2022-01-07 11:55 UTC, iTiky commented on api/rest/api.go
> +		func(r chi.Router) {
Дабы улучшить читабельность, я бы `func` перенес на строчку выше, так код будет компактнее. Т.е. как в примерах chi:
```go
r.Route("/articles", func(r chi.Router) {
    r.With(paginate).Get("/", listArticles)   
}
```

2022-01-07 11:55 UTC, iTiky commented on api/rest/api_test.go
> +	if err != nil {
-> `require.NoError(t, err)` так тесты будут короче

2022-01-07 11:55 UTC, iTiky commented on api/rest/metric_test.go
>  	defer mockCtrl.Finish()
Могу ошибаться, но мне казалось в доках gomock они пишут, что с какой-то версии можно не делать finish

2022-01-07 11:55 UTC, iTiky commented on model/metric.go
> +func (m *Metric) StringValue() string {
В Go есть стандартный интерфейс `fmt.Stringer`, лучше писать в таком стиле. Т.е.:
`func (m Metric) String() string`
Этот метод не меняет объект, поэтому pointer receiver тут не нужен (это вводит в заблуждение).

2022-01-07 11:55 UTC, iTiky commented on service/agent/agent.go
> +	ctx2, cancel := context.WithTimeout(ctx, a.config.PostTimeout)
Тут можно проще: `ctx, cancel := context...`, т.е. ты переопределяешь контекст. Иногда функции нужно кучу раз пересоздать контекст на базе другого, каждый раз создавать `ctx2`, `ctx3` мучительно больно =)

2022-01-15 13:36 UTC, merged